// manual-multi-page/react/App.tsx
import { useEffect, useRef, useState } from 'react';
import {
    defineComponents,
    DocumentReaderService,
    DocumentReaderDetailType,
    TransactionEvent,
    DocumentReaderWebComponent,
    ResponseCode,
    EventActions,
    InternalScenarios,
    DocumentReaderResponseType,
} from '@regulaforensics/vp-frontend-document-components';
import Results from './Results';
import './styles.css';

enum Status {
    Start,
    Result,
    Processing,
}

const App = () => {
    const containerRef = useRef<HTMLDivElement>(null);
    const elemRef = useRef<DocumentReaderWebComponent>(null);
    const [response, setResponse] = useState<DocumentReaderResponseType | null>(null);
    const [status, setStatus] = useState<Status>(Status.Start);
    const [morePagesAvailable, setMorePagesAvailable] = useState(false);

    const listener = async (data: CustomEvent<DocumentReaderDetailType | TransactionEvent>) => {
        const action = data.detail.action;

        if (action === EventActions.PROCESS_FINISHED) {
            const status = data.detail.data?.status;
            const isFinishStatus = status === ResponseCode.OK || status === ResponseCode.TIMEOUT;
            const responseData = data.detail.data;

            if (isFinishStatus && responseData?.response) {
                setResponse(responseData.response);
                setStatus(Status.Result);
                setMorePagesAvailable(!!responseData?.response?.rawResponse.morePagesAvailable);
            }
        }
        if (data.detail?.action === EventActions.CLOSE || data.detail?.action === EventActions.CAMERA_PROCESS_CLOSED) {
            setResponse(null);
            setMorePagesAvailable(false);
            setStatus(Status.Start);
        }
    };

    const startDocument = () => {
        if (!window.RegulaDocumentSDK) return;

        void window.RegulaDocumentSDK.startNewDocument();
        setStatus(Status.Processing);
    };

    const startNewPage = () => {
        if (!window.RegulaDocumentSDK) return;

        void window.RegulaDocumentSDK.startNewPage();
        setStatus(Status.Processing);
    };

    useEffect(() => {
        window.RegulaDocumentSDK = new DocumentReaderService();
        window.RegulaDocumentSDK.recognizerProcessParam = {
            processParam: {
                scenario: InternalScenarios.MrzAndLocate,
                multipageProcessing: true,
            },
        };

        defineComponents().then(() => window.RegulaDocumentSDK.initialize());
        // To use the document-reader component on test environments, you have to set the base64 license
        // defineComponents().then(() => window.RegulaDocumentSDK.initialize({ license: 'YOUR_BASE64_LICENSE_KEY' }));

        const containerRefCurrent = containerRef.current;

        if (!containerRefCurrent) return;

        containerRefCurrent.addEventListener('document-reader', listener);

        return () => {
            window.RegulaDocumentSDK.shutdown();
            containerRefCurrent.removeEventListener('document-reader', listener);
        };
    }, []);

    useEffect(() => {
        const elementRefCurrent = elemRef.current;

        if (elementRefCurrent && status === Status.Processing) {
            elementRefCurrent.settings = {
                manualMultipageMode: true
            };
        }
    }, [status]);

    return (
        <div ref={containerRef}>
            {status === Status.Start && (
                <div className='buttons'>
                    <button className='button' onClick={startDocument}>
                        Open Document Reader
                    </button>
                </div>
            )}
            {status === Status.Result && (
                <>
                    <div className='buttons'>
                        <button className='button' onClick={startDocument}>
                            Try again
                        </button>
                        {morePagesAvailable && (
                            <button className='button' onClick={startNewPage}>
                                Start new page
                            </button>
                        )}
                    </div>
                    {response && (
                        <div className='results-container'>
                            <Results response={response} />
                        </div>
                    )}
                </>
            )}
            {status === Status.Processing && (
                <div className='reader-container'>
                    <document-reader new-layout ref={elemRef} />
                </div>
            )}
        </div>
    );
};

export default App;

// angular/document-reader/src/app/app.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';

import { ReaderComponent } from './components/reader.component';
import {
  EventActions,
  defineComponents,
  DocumentReaderService,
  InternalScenarios,
  DocumentReaderDetailType,
  TransactionEvent
} from '@regulaforensics/vp-frontend-document-components';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  imports: [ReaderComponent],
})
export class AppComponent implements OnInit, OnDestroy {
  isOpen: boolean = false;

  ngOnInit() {
    window.RegulaDocumentSDK = new DocumentReaderService();
    window.RegulaDocumentSDK.recognizerProcessParam = {
      processParam: {
        scenario: InternalScenarios.MrzAndLocate,
        multipageProcessing: true,
      },
    };
    window.RegulaDocumentSDK.imageProcessParam = {
      processParam: {
        scenario: InternalScenarios.MrzAndLocate,
      },
    };

    defineComponents().then(() => window.RegulaDocumentSDK.initialize());
    // To use the document-reader component on test environments, you have to set the base64 license
    // defineComponents().then(() => window.RegulaDocumentSDK.initialize({ license: 'YOUR_BASE64_LICENSE_KEY' }));
  }

  ngOnDestroy() {
    window.RegulaDocumentSDK.shutdown();
  }

  documentReaderHandler(data: CustomEvent<DocumentReaderDetailType | TransactionEvent>) {
    if (data.detail.action === EventActions.PROCESS_FINISHED) {
      const status = data.detail.data?.status;
      const isFinishStatus = status === 1 || status === 2;

      if (!isFinishStatus || !data.detail.data?.response) return;
      console.log(data.detail.data.response);
    }

    if (data.detail?.action === EventActions.CLOSE) {
      this.isOpen = false;
    }
  }
}

<div class="container" (document-reader)="documentReaderHandler($event)">
  @if (isOpen) {
    <app-reader></app-reader>
  } @else {
    <button (click)="isOpen = true">Open component</button>
  }
</div>
