// ui-components/react/App.tsx
import { useEffect, useState } from 'react';
import {
  DocumentReaderApi,
  Configuration,
  Scenario,
  ProcessResponse,
  ProcessRequest,
} from '@regulaforensics/document-reader-webclient';
import { ResultTabs } from './components/ResultTabs';
import { Menu } from './components/Menu';
import './styles.css';

interface ProcessingData {
  mode: 'sample' | 'upload'
  base64: string
}

export const App = () => {
  const [processingData, setProcessingData] = useState<ProcessingData | null>(null);
  const [response, setResponse] = useState<ProcessResponse | null>(null);
  const [request, setRequest] = useState<ProcessRequest | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const showComponent = isLoading || (!isLoading && response);

  useEffect(() => {
    if (!processingData) return;

    const configuration = new Configuration({ basePath: 'https://api.regulaforensics.com' });
    const api = new DocumentReaderApi(configuration);
    const request = {
      images: [ processingData.base64 ],
      processParam: {
        scenario: Scenario.FULL_PROCESS,
        alreadyCropped: processingData.mode === 'sample',
      }
    };

    setIsLoading(true);
    setResponse(null);
    api.process(request).then((res) => {
      setResponse(res.rawResponse);
      setRequest(request);
      setIsLoading(false);
    });
  }, [processingData]);

  return (
    <div className='container'>
      <Menu setProcessingData={ setProcessingData } />
      { showComponent && (
        <ResultTabs
          response={ response }
          request={ request }
          language='en'
        />
      ) }
    </div>
  );
};

// ui-components/angular/src/app/app.component.ts
import { DocumentReaderApi, Configuration, Scenario } from '@regulaforensics/document-reader-webclient';

import { Component } from '@angular/core';
import { ComponentProps } from 'react';
import { ReactWrapper } from './components/react-wrapper/react-wrapper.component';
import { ReactComponent } from './components/react-component/react-component';
import { MenuComponent } from './components/menu/menu.component';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  imports: [ReactWrapper, MenuComponent],
})
export class AppComponent {
  processingData: { mode: 'sample' | 'upload'; base64: string } | null = null;
  isLoading = false;
  processingResults = ReactComponent;
  processingResultsProps: ComponentProps<typeof ReactComponent> = {
    response: null,
    request: null,
    language: 'en'
  }

  setProcessingData(data: { mode: 'sample' | 'upload'; base64: string }) {
    this.processingData = data;
    this.processImage();
  }

  processImage() {
    if (!this.processingData) return;

    const configuration = new Configuration({ basePath: 'https://api.regulaforensics.com' });
    const api = new DocumentReaderApi(configuration);
    const request = {
      images: [this.processingData.base64],
      processParam: {
        scenario: Scenario.FULL_PROCESS,
        alreadyCropped: this.processingData.mode === 'sample',
      }
    };

    this.isLoading = true;
    this.processingResultsProps = { ...this.processingResultsProps, response: null };

    api.process(request).then((res) => {
      this.processingResultsProps = {
        ...this.processingResultsProps,
        response: res.rawResponse,
        request
      };
      this.isLoading = false;
    });
  }

  get showComponent(): boolean {
    return this.isLoading || (!this.isLoading && this.processingResultsProps.response !== null);
  }
}

<div class="container">
  <app-menu (processingData)="setProcessingData($event)"></app-menu>
  @if (showComponent) {
    <div [reactComponent]="processingResults" [props]="processingResultsProps"></div>
  }
</div>
