// ui-components/angular/src/app/components/menu/menu.component.ts
import { Component, ElementRef, EventEmitter, Output, ViewChild } from '@angular/core';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent {
  @Output() processingData = new EventEmitter<{ mode: 'sample' | 'upload'; base64: string }>();
  @ViewChild('fileInput') myInput!: ElementRef;

  convertToBase64(file: File, mode: 'sample' | 'upload') {
    const reader = new FileReader();
    reader.onloadend = () => {
      if (typeof reader.result === 'string') {
        const [_, result] = reader.result.split(',');
        this.processingData.emit({ mode, base64: result });
      }
    };
    reader.readAsDataURL(file);
  }

  handleImageClick(event: Event) {
    const target = event.target as HTMLImageElement;
    const url = target.src;

    fetch(url)
    .then((response) => response.blob())
    .then((blob) => {
      const file = new File([blob], 'image.jpg', { type: blob.type });
      this.convertToBase64(file, 'sample');
    })
    .catch((error) => console.error('Error fetching image:', error));
  }

  handleImageUpload(event: Event) {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (file) {
      this.convertToBase64(file, 'upload');
    }
  }

  triggerFileInput() {
    this.myInput.nativeElement.click()
  }
}

<div class="menu">
    <div class="samples">
        <div class="title">Choose image:</div>
        <div class="images">
            <img
                src="/assets/passport.jpg"
                (click)="handleImageClick($event)"
                alt="passport"
            />
            <img
                src="/assets/visa.jpg"
                (click)="handleImageClick($event)"
                alt="visa"
            />
        </div>
    </div>
    <div class="upload">
        <button class="button" (click)="triggerFileInput()">Upload your own</button>
        <input
            #fileInput
            style="display: none;"
            type="file"
            accept="image/*"
            (change)="handleImageUpload($event)"
        />
    </div>
</div>

// ui-components/react/components/Menu.tsx
import { ChangeEvent, FC, useRef, MouseEvent } from 'react';
import passport from '../static/passport.jpg';
import visa from '../static/visa.jpg';

interface MenuProps {
  setProcessingData: (processingData: { mode: 'sample' | 'upload', base64: string }) => void
}

export const Menu: FC<MenuProps> = ({
  setProcessingData,
}) => {
  const inputRef = useRef<HTMLInputElement>(null);

  const handleButtonClick = () => {
    inputRef.current?.click();
  };

  const handleImageUpload = (event: ChangeEvent<HTMLInputElement>) => {
    if (!event.target.files?.[0]) return;
    convertToBase64({ file: event.target.files?.[0], mode: 'upload' });
  };

  const convertToBase64 = ({ file, mode }: { file: File, mode: 'sample' | 'upload' }) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      if (typeof reader.result === 'string') {
        const [_, result] = reader.result.split(',');
        setProcessingData({ mode, base64: result });
      }
    };
    reader.readAsDataURL(file);
  };

  const handleImageClick = async (event: MouseEvent<HTMLImageElement>) => {
    const response = await fetch(event.currentTarget.src);
    const blob = await response.blob();
    const file = new File([blob], 'image.jpg', { type: blob.type });
    convertToBase64({ file, mode: 'sample' });
  };

  return (
    <div className='menu'>
      <div className='samples'>
        <div className='title'>Choose image:</div>
        <div className='images'>
          <img src={ passport } onClick={ handleImageClick } alt='passport'/>
          <img src={ visa } onClick={ handleImageClick } alt='visa'/>
        </div>
      </div>
      <div className='upload'>
        <button
          className='button'
          onClick={ handleButtonClick }
        >
          Upload your own
        </button>
        <input
          ref={ inputRef }
          style={{ display: 'none' }}
          type='file'
          accept='image/*'
          onChange={ handleImageUpload }
        />
      </div>
    </div>
  )
}
